### ISSUE TITLE
Incorrectly displayed name

### ISSUE THREAD

**Issue by Andrew-Tierno** [Vedaad-Shakib/HHMS#13]
When switching from weekly view to daily view and then back to weekly view the "Hello" portion in the top right corner switched from saying "Hi, Andrew" to "Hi, N". This seems only to be an issue in weekly view as it reports Andrew when in daily view. 

Pictures attached. 

In Daily View:
![screen shot 2015-02-23 at 11 09 24 am](https://cloud.githubusercontent.com/assets/3424291/6334973/e288f4de-bb4c-11e4-9941-c2e4a3410e47.png)

In Weekly View:
![screen shot 2015-02-23 at 11 09 32 am](https://cloud.githubusercontent.com/assets/3424291/6334974/e28bb6c4-bb4c-11e4-9636-c0a5c5606fe4.png)

**Comment by Vedaad-Shakib** [comment]
Fixed.
