### ISSUE TITLE
Properly link resources attached in assignments

### ISSUE THREAD

**Issue by Andrew-Tierno** [Vedaad-Shakib/HHMS#21]
PCR uses relative links, for instance 

```
href="Common/AttachmentRender.aspx?id=10960&type=Assessment"
```

The actual link is:
https://webappsca.pcrsoft.com/Clue/Common/AttachmentRender.aspx?id=10960&type=Assessment
The general form is probably 
https://webappsca.pcrsoft.com/Clue/HREF

**Comment by Vedaad-Shakib** [comment]
Fixed.
