### ISSUE TITLE
3 Classes Missing 

### ISSUE THREAD

**Issue by Andrew-Tierno** [Vedaad-Shakib/HHMS#22]
As of 067b3ea, three of my seven classes are not being shown in the schedule. There is no relevant output in the console (baring the "moved to here" reported in issue #20). Reverting back to 7379c19 fixed the issue. If it has any relevance the classes missing are Honors French 4, Competitive Forensics, and AP European History. Image attached.

![screen shot 2015-03-04 at 6 16 10 pm](https://cloud.githubusercontent.com/assets/3424291/6497945/31a5be26-c29b-11e4-94a0-64e86da88c39.png)

**Comment by Vedaad-Shakib** [comment]
It works for me... Are you sure you just don't have homework in the other classes?

**Comment by Andrew-Tierno** [comment]
Even if I didn't have homework (which I do) the rows should still appear, though blank. It's possible that whatever you've added (perhaps monthPost.txt) is user specific. Perhaps see if a different account produces the same monthPost file?

**Comment by Vedaad-Shakib** [comment]
If you don't have homework from a particular class, it will not appear. Maybe add that as a bug, but it's not high priority.

**Comment by Vedaad-Shakib** [comment]
That's really strange... I'll work on it after I finish prepping for chemistry and Huffy essay.

**Comment by Vedaad-Shakib** [comment]
Ohhh... I think I know what's happening here: the viewstate somehow also captures your classes...

The only classes you're seeing are the classes that I have in common with you.

**Comment by Vedaad-Shakib** [comment]
Okay. Not doing this anymore, so this should not be a problem.
