### ISSUE TITLE
Daily View Due Later doesn't capture all assignments

### ISSUE THREAD

**Issue by Andrew-Tierno** [Vedaad-Shakib/HHMS#28]
There are discrepancies between Daily View "Due Later" and assignments due later in the week from week view.

Weekly:
![screen shot 2015-03-10 at 3 29 41 pm](https://cloud.githubusercontent.com/assets/3424291/6586850/6d8f3202-c73a-11e4-9b8d-c53be6be0dc1.png)

Daily:
![screen shot 2015-03-10 at 3 29 56 pm](https://cloud.githubusercontent.com/assets/3424291/6586851/6d8fd55e-c73a-11e4-9448-7a62229ddab1.png)

**Comment by Vedaad-Shakib** [comment]
Already a previous issue.
